In [53]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [54]:
inc = np.array([Husband_Income,Wife_Income,Mother_In_Law_Income])
inc = inc.transpose()
print(inc)

[[100 150  90]
 [220 200  80]
 [140 130 100]]


In [55]:
cons = np.array([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption])
cons = cons.transpose()
print(cons)

[[ 50 100 100]
 [ 50  80  20]
 [ 60 140 140]]


In [56]:
print(inc)
inc_after_taxe = inc - inc*0.13
print(inc_after_taxe)


[[100 150  90]
 [220 200  80]
 [140 130 100]]
[[ 87.  130.5  78.3]
 [191.4 174.   69.6]
 [121.8 113.1  87. ]]


In [58]:
p = inc_after_taxe-cons
print(p)


[[ 37.   30.5 -21.7]
 [141.4  94.   49.6]
 [ 61.8 -26.9 -53. ]]


In [60]:
A = np.array([[1,-1,2,4,0],[8,2,0,5,3],[0,1,2,1,2]])
B = np.array([[1,0,1,0],[0,0,2,-1],[1,0,1,1],[0,1,1,1],[1,1,0,-1]])

print(A@B)


[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]
