In [49]:
import numpy as np
import pandas as pd

In [50]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [51]:
print(A@x)


[26 30]


In [52]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [53]:
print(B@A)


[[  2   9  11  14]
 [  8 -10 -14 -11]]


In [54]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [55]:
A = np.array([x,y,z]).T

print(A.T@A)



[[22  3  0]
 [ 3  7  0]
 [ 0  0  3]]


In [56]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7],
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0],
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                },
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5],
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4],
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2]
                                },
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])


In [57]:
revenue = Count_DF.values*Price_DF.values
print(revenue)

[[20.   7.5 12.  12.  10. ]
 [ 3.6 52.5  3.  25.   6. ]
 [24.  24.   0.  15.   8. ]
 [ 7.2  9.6 50.4 11.2 10. ]
 [15.  87.5 54.  25.  27. ]
 [50.  15.   6.  34.  30. ]
 [24.2  1.   6.  12.5 34. ]
 [31.5  0.  77.5 31.  56. ]]


In [58]:
commission = [0.2, 0.2, 0.3, 0.1, 0.1]

In [59]:
salon_revenue = revenue@commission
print(salon_revenue)


[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [61]:
profit = revenue@np.ones(5)-revenue@commission

print(profit)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [63]:
A = np.array([[1,2],[2,5]])
print(np.linalg.inv(A))



[[ 5. -2.]
 [-2.  1.]]


In [69]:
A = np.array([[1,1],[1,7]])
Ainv = np.linalg.inv(A)
print(Ainv)
b = np.array([2,3])
print(Ainv@b)

[[ 1.16666667 -0.16666667]
 [-0.16666667  0.16666667]]
[1.83333333 0.16666667]


In [70]:
A=np.array([[4,-4,0],[7,2,9],[-1,5,4]])
print(np.linalg.matrix_rank(A))

2


In [71]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
np.linalg.matrix_rank(A)

3

In [72]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [76]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

A = np.array([v1,v2,v3,v4])
np.linalg.matrix_rank(A)



4

In [86]:
Agr=A
print(Agr)

[[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


In [87]:
print(np.linalg.det(Agr))

3716647.9999999995


In [88]:
print(np.linalg.inv(Agr))



[[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]


In [89]:
A = [[4,-4,0],[7,2,9],[-1,5,4]]
Aexp = [[4,-4,0],[7,2,9],[-1,5,4],[7,3,10]]

r_Aexp = np.linalg.matrix_rank(Aexp)
r_A = np.linalg.matrix_rank(A)


In [91]:
A = [[1,1],[1,2],[1,1]]



In [100]:
A = np.array([[1,-3,1,1],[2,1,2,-1]]).T
b = np.array([1,4,5,0])
bn = A.T@b
Agr = A.T@A
Agrinv =  np.linalg.inv(Agr)
print(Agrinv@bn)


[-0.5  1.6]
