In [83]:
import numpy as np
import pandas as pd

In [84]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
share_living_space = round(apartment[1]/apartment[0],2)
apartment = np.delete(apartment,[0,1])
apartment = np.append(apartment,share_living_space)

print(apartment)
print(len(apartment))

[1.90e+01 2.00e+00 6.06e+04 2.00e+00 5.30e-01]
5


In [85]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85],
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65],
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5],
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10],
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

Hut_Paradise_values = Hut_Paradise_DF.values
h5 = Hut_Paradise_values[4]
print(h5)

f = Hut_Paradise_values[:,3]
print(f)

f3 = f[2]
print(f3)

print(len(f))

[40 33  1  6 20 16]
[ 5 12 10  3  6 13  8 21  5]
10
9


In [86]:
print(Hut_Paradise_values[:,1]-Hut_Paradise_values[:,5])



[13 12 15 13 17  9 20 15 25]


In [87]:
print(Hut_Paradise_values[:,0]*0.4)

[26. 28. 48. 14. 16. 20. 40. 36. 34.]


In [88]:
demo = Hut_Paradise_values[:,4]
time = np.array([10,20,30,15,5,40,20,8,20])

full_time = demo@time


In [89]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])


uv = u@v
uw = u@w
vw = v@w

In [90]:
l1 = 2*v-3*w
l1u = l1@u

In [91]:
u_norm = u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)
